---
apiVersion: v1
kind: Service
metadata:
  name: purpleaip
  namespace : aip-ml
  labels:
    app: purpleaip
spec:
  selector:
    app: purpleaip
  ports:
  - name: purpleaip
    protocol: TCP
    port: 5901
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: purpleaip-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls: ""
spec:
  rules:
  - host: purpleaip.nautilus.optiputer.net
    http:
      paths:
      - backend:
          serviceName: purpleaip
          servicePort: 5901
