apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isaac
  template:
    metadata:
      labels:
        app: isaac
    spec:
      nodeSelector:
#        kubernetes.io/hostname: suncave-12
      tolerations:
      - key: "region"
        operator: "Equal"
        value: "allow"
        effect: "NoSchedule"
      - key: "nautilus.io/nogl"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "nautilus.io/vis"
        operator: "Exists"
        effect: "NoSchedule"
      - key: nautilus.io/suncave
        effect: NoSchedule
        operator: Exists
      hostname: isaac
      containers:
      - name: isaac
        image: gitlab-registry.nautilus.optiputer.net/prp/isaac:latest
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: NETWORKING
          value: "yes"
        - name: container
          value: "docker"
        - name: SIZEW
          value: "1920"
        - name: SIZEH
          value: "1200"
        - name: CDEPTH
          value: "24"
        - name: SHARED
          value: "TRUE"
        - name: VNCPASS
          valueFrom:
            secretKeyRef:
              name: isaac-egl-pass
              key: password
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
#          privileged: true
        ports:
          - containerPort: 5901
            protocol: TCP
        resources:
          limits:
            memory: "32Gi"
            cpu: "8"
            ephemeral-storage: 32Gi
          requests:
            memory: "32Gi"
            cpu: "8"
            ephemeral-storage: 32Gi
        volumeMounts:
        - mountPath: /home/user
          name: isaac-root-vol
        - mountPath: /dev/shm
          name: dshm
      volumes:
        - name: isaac-root-vol
          persistentVolumeClaim:
            claimName: isaac-root-vol
        - name: dshm
          emptyDir:
            medium: Memory

