apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isaacaip-root-vol
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
