apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: purpleaip-root-vol
  namespace : aip-ml
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
