apiVersion: apps/v1
kind: Deployment
metadata:
  name: purpleaip
  namespace : aip-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purpleaip
  template:
    metadata:
      labels:
        app: purpleaip
    spec:
      nodeSelector:
        kubernetes.io/hostname: suncave-20
      tolerations:
      - key: "region"
        operator: "Equal"
        value: "allow"
        effect: "NoSchedule"
      - key: "nautilus.io/nogl"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "nautilus.io/vis"
        operator: "Exists"
        effect: "NoSchedule"
      - key: nautilus.io/suncave
        effect: NoSchedule
        operator: Exists
      - key: nautilus.io/suncave
        effect: NoSchedule
        operator: Exists
      - key: nautilus.io/nogltest
        effect: NoSchedule
        operator: Exists
      hostname: purpleaip
      containers:
      - name: purpleaip
        image: gitlab-registry.nautilus.optiputer.net/aip_197_accchi/purple_nl/isaacaip:latest
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: NETWORKING
          value: "yes"
        - name: container
          value: "docker"
        - name: SIZEW
          value: "1920"
        - name: SIZEH
          value: "1200"
        - name: CDEPTH
          value: "24"
        - name: SHARED
          value: "TRUE"
        - name: VNCPASS
          valueFrom:
            secretKeyRef:
              name: purpleaip-egl-pass
              key: password
        securityContext:
          capabilities:
            add: ["SYS_TTY_CONFIG"]
#            add: ["NET_ADMIN"]
        ports:
          - containerPort: 5901
            protocol: TCP
        resources:
          limits:
            memory: "16Gi"
            cpu: "8"
            ephemeral-storage: 16Gi
            nvidia.com/gpu: 1
            hostdev.k8s.io/dev_dri_card0: 1
            hostdev.k8s.io/dev_dri_card1: 1
            hostdev.k8s.io/dev_dri_renderD128: 1
            hostdev.k8s.io/dev_dri_renderD129: 1
            hostdev.k8s.io/dev_tty63: 1
            # hostdev.k8s.io/dev_video0: 1
          requests:
            memory: "16Gi"
            ephemeral-storage: 16Gi
            cpu: "8"
            nvidia.com/gpu: 1
            hostdev.k8s.io/dev_dri_card0: 1
            hostdev.k8s.io/dev_dri_card1: 1
            hostdev.k8s.io/dev_dri_renderD128: 1
            hostdev.k8s.io/dev_dri_renderD129: 1
            hostdev.k8s.io/dev_tty63: 1
            # hostdev.k8s.io/dev_video0: 1
        volumeMounts:
        - mountPath: /home/user
          name: purpleaip-root-vol
        - mountPath: /dev/dri
          name: drm
        - mountPath: /dev/shm
          name: dshm
      volumes:
        - name: purpleaip-root-vol
          persistentVolumeClaim:
            claimName: purpleaip-root-vol
        - name: drm
          hostPath:
            path: /dev/dri
        - name: dshm
          emptyDir:
            medium: Memory
