apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xilinx-casper-tools-vol
  namespace: casper
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
