apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xilinx-casper-root-vol
  namespace: casper
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
